apiVersion: v1
kind: Pod
metadata:
  name: log-sender
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: log-sender
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
