apiVersion: v1
kind: Secret
metadata:
  name: aiops-secrets
  namespace: observability
type: Opaque
stringData:
  OLLAMA_MODEL: gemma3:12b
  PROMETHEUS_URL: http://prometheus-server.observability:9090
  LOKI_URL: http://loki.observability:3100
  TEMPO_URL: http://tempo.observability:3200
